theme: jekyll-theme-minimal
title: "How I learned React JS by myself"
description: "This is a simple blog detailing my learning process of React JS. This started as a project at school and I intended to continue this to share my journey. React JS is a highly-performing and powerful library that has become increasingly popular nowadays. If I can self-learn, you can do it too. <br> WMDD 4992 Directed Studies <br> Mai Khanh (Maggie) Vu"
logo: "reactjs-logo.png"
