theme: jekyll-theme-minimal
title: "How I learned React JS by myself"
description: "This is a simple blog detailing my learning process of React JS. React JS is a highly-performing and powerful library that has become increasingly popular nowadays. This started as a project at school and I intended to keep it going to share my journey. If I can self-learn, you can too. <em><br> WMDD 4992 Directed Studies <br> Mai Khanh (Maggie) Vu</em>"
logo: "reactjs-logo.png"
