theme: jekyll-theme-minimal

title: WMDD 4992 - Portfolio Deliverables
description: A simple blog for WMDD 4992 - Directed Studies by Mai Khanh (Maggie) Vu


logo: [Location of the logo]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
